name: jest-timing-action

# push or pull request on the master branch
on:
  pull_request:
    branches: [ master ]
jobs:
  pr_check:
    runs-on: ubuntu-latest
    name: Post Test Timing deltas on PR
    steps:
    - uses: actions/checkout@v2
    - name: PR Action
      uses: javierfernandes/jest-timing-action@master
      with:
        threshold: 25
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
